# Numpy

Numpy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

Topics Array:
1. Creation
   * Zeros
   * Ones
   * Empty 
   * Full
2. Indexing & Slicing 
3. Reshaping
4. Splitting

Mathematical Operations:
1. Basic Operations
2. Dot Product
3. Sum
4. Min
5. Max
6. Mean
7. Standard Deviation
8. Subtract
9. Add
10. Multiply
11. Divide

Special Functions:
1. argmax
2. argmin
3. flatten
4. transpose

Copies and views


In [4]:
import numpy as np

## Array Creation

In [16]:
# Create an array from a list
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
# Create a 2D array from a list of lists
b = np.array([[1, 2, 3], [4, 5, 6]])

In [4]:
# Create a 3D array from a list of lists
c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [5]:
# Create an array of zeros
d = np.zeros((2, 3))

In [6]:
# Create an array of ones
e = np.ones((2, 3))

In [7]:
# Create an array of random values
f = np.random.random((2, 3))

In [8]:
# Create an array of evenly spaced values
g = np.arange(10)

In [9]:
# Create an array of evenly spaced values
h = np.linspace(0, 1, 6)

In [10]:
# Create an array of random integers
i = np.random.randint(0, 10, (2, 3))

In [11]:
# Create an identity matrix
j = np.eye(3)

In [12]:
# Create an array of uninitialized values
k = np.empty(3)

In [13]:
# Create an array of uninitialized values
l = np.full((2, 3), 7)

In [14]:
# Create an array of uninitialized values
m = np.empty((2, 3))

## Array Indexing

In [17]:
# Get a single element
a[0]

1

In [18]:
# Get a single element
b[0, 0]

1

In [20]:
# Get a row
b[0]

array([1, 2, 3])

In [21]:
# Get a column
b[:, 0]

array([1, 4])

In [22]:
# Get a subarray
b[:2, :2]

array([[1, 2],
       [4, 5]])

In [23]:
# Get a subarray
b[0, 1:]

array([2, 3])

In [24]:
# Get a subarray
b[0, 1:]

array([2, 3])

## Array Slicing

In [25]:
# Create an array
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [26]:
# Get the first two rows and the first three columns
b = a[:2, :3]

In [27]:
# Get the first two rows and the first three columns
c = a[:2, :3]

In [28]:
# Get the first two rows and the first three columns
d = a[:2, :3]

In [ ]:
# Get the first two rows and the first three columns

## Array Reshaping

In [34]:
# Create an array
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
# Get the shape of an array
a.shape

(2, 3)

In [33]:
# Reshape an array
b = a.reshape((3, 2))
b

array([[1, 2],
       [3, 4],
       [5, 6]])

## Array Splitting

In [41]:
# Create an array
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [42]:
# Split an array horizontally
b, c = np.hsplit(a, [2])
b,c

(array([[1, 2],
        [4, 5],
        [7, 8]]),
 array([[3],
        [6],
        [9]]))

In [43]:
# Split an array vertically
d, e = np.vsplit(a, [2])
d, e

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]]))

## Mathematical Operations

In [45]:
# Create an array
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [46]:
# Add two arrays
b = np.array([[5, 6], [7, 8]])
a + b

array([[ 6,  8],
       [10, 12]])

In [47]:
# Subtract two arrays
a - b

array([[-4, -4],
       [-4, -4]])

In [48]:
# Multiply two arrays
a * b

array([[ 5, 12],
       [21, 32]])

In [49]:
# Divide two arrays
a / b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [50]:
# Square root of an array
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [51]:
# Exponential of an array
np.exp(a)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [52]:
# Dot product of two arrays
np.dot(a, b)

array([[19, 22],
       [43, 50]])

In [53]:
# Sum of all elements in an array
a.sum()

10

In [54]:
# Minimum value in an array
a.min()

1

In [55]:
# Maximum value in an array
a.max()

4

In [56]:
# Mean of all elements in an array
a.mean()

2.5

In [57]:
# Standard deviation of all elements in an array
a.std()

1.118033988749895

In [59]:
# difference between two arrays
np.subtract(a,b)

array([[-4, -4],
       [-4, -4]])

In [60]:
# sum of two arrays
np.add(a,b)

array([[ 6,  8],
       [10, 12]])

In [61]:
# product of two arrays
np.multiply(a,b)

array([[ 5, 12],
       [21, 32]])

In [62]:
# division of two arrays
np.divide(a,b)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

## Special Functions

In [83]:
# Create an array
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [64]:
# Index of the maximum value
np.argmax(a)

3

In [65]:
# Index of the minimum value
np.argmin(a)

0

In [66]:
# Norm of an array
np.linalg.norm(a)

5.477225575051661

In [67]:
# distance between two arrays
np.linalg.norm(a-b)

8.0

In [68]:
a.flatten()

array([1, 2, 3, 4])

In [82]:
a.squeeze(axis=None)

array([[1, 2],
       [3, 4]])

In [84]:
# Transpose of an array
a.T

array([[1, 3],
       [2, 4]])

## Copies and views

In [5]:
# Create an array
a = np.array([1, 2, 3, 4])


In [6]:
view_a_1 = a.view()
view_a_2 = a
copy_a = a.copy()

In [7]:
a

array([1, 2, 3, 4])

In [8]:
a[0] = 5

In [9]:
view_a_1

array([5, 2, 3, 4])

In [10]:
view_a_2

array([5, 2, 3, 4])

In [11]:
copy_a

array([1, 2, 3, 4])

In [12]:
id(a)

13015650672

In [13]:
id(view_a_1)

13015653168

In [14]:
id(view_a_2)

13015650672

In [15]:
id(copy_a)

13015653072